/**
 * Bảng tra cứu ánh xạ từ khóa tiếng Việt / tiếng Anh sang trường hệ thống
 * Tuân thủ nguyên lý Đơn trách nhiệm (SRP) và Mở/Đóng (OCP)
 */

export const MODULE_KEY_MAPS: Record<string, Record<string, string>> = {
  'audit-plans': {
    'năm kế hoạch': 'year',
    năm: 'year',
    nam: 'year',
    year: 'year',
    'plan year': 'year',
    'năm thực hiện': 'year',
    'tên kế hoạch': 'name',
    'tên kế hoạch kiểm toán': 'name',
    'kế hoạch kiểm toán': 'name',
    'kế hoạch': 'name',
    tên: 'name',
    name: 'name',
    'plan name': 'name',
    'audit plan name': 'name',
    'phòng ktnb phụ trách': 'ownerTeam',
    'phòng ktnb': 'ownerTeam',
    'đơn vị thực hiện': 'ownerTeam',
    'phòng phụ trách': 'ownerTeam',
    'owner team': 'ownerTeam',
    ownerteam: 'ownerTeam',
    'nhóm ktnb': 'ownerTeam',
    'mã đối tượng kt': 'universeCode',
    'mã đối tượng': 'universeCode',
    'mã quy trình': 'universeCode',
    'mã đơn vị': 'universeCode',
    'mã dvkd': 'universeCode',
    'universe id': 'universeId',
    'universe code': 'universeCode',
    code: 'universeCode',
    'tên đối tượng / quy trình kiểm toán': 'unitName',
    'tên đối tượng kiểm toán': 'unitName',
    'tên đối tượng': 'unitName',
    'đối tượng kiểm toán': 'unitName',
    'đối tượng': 'unitName',
    'tên quy trình': 'unitName',
    'quy trình kiểm toán': 'unitName',
    'quy trình': 'unitName',
    'đơn vị kiểm toán': 'unitName',
    'đơn vị': 'unitName',
    'unit name': 'unitName',
    'process name': 'unitName',
    'phân loại': 'auditCategory',
    'phân loại đối tượng': 'auditCategory',
    'nhóm kiểm toán': 'auditCategory',
    category: 'auditCategory',
    'audit category': 'auditCategory',
    'mức độ rủi ro': 'riskLevel',
    'mức rủi ro': 'riskLevel',
    'hạng rủi ro': 'riskLevel',
    'rủi ro': 'riskLevel',
    risklevel: 'riskLevel',
    'risk level': 'riskLevel',
    'risk rating': 'riskLevel',
    'quý dự kiến': 'targetQuarter',
    quý: 'targetQuarter',
    'target quarter': 'targetQuarter',
    quarter: 'targetQuarter',
    'tháng dự kiến': 'scheduledMonth',
    tháng: 'scheduledMonth',
    'scheduled month': 'scheduledMonth',
    month: 'scheduledMonth',
    'ngày công dự kiến': 'estDays',
    'ngày công': 'estDays',
    'số ngày công': 'estDays',
    mandays: 'estDays',
    'est days': 'estDays',
    'estimated days': 'estDays',
    estdays: 'estDays',
    'số lượng ktv': 'ktvCount',
    'số ktv': 'ktvCount',
    'lượt ktv': 'ktvCount',
    'số ktv tham gia': 'ktvCount',
    'ktv count': 'ktvCount',
    'auditor count': 'ktvCount',
    ktvcount: 'ktvCount',
    'trưởng đoàn dự kiến': 'leadAuditorName',
    'trưởng đoàn': 'leadAuditorName',
    'lead auditor': 'leadAuditorName',
    'lead auditor name': 'leadAuditorName',
    'team leader': 'leadAuditorName',
    'căn cứ / giải trình lựa chọn': 'justification',
    'căn cứ / giải trình': 'justification',
    'giải trình': 'justification',
    'lý do chọn': 'justification',
    'lý do lựa chọn': 'justification',
    'căn cứ': 'justification',
    'cơ sở lựa chọn': 'justification',
    justification: 'justification',
    reason: 'justification',
    'trạng thái kế hoạch': 'status',
    'trạng thái': 'status',
    status: 'status',
    'ý kiến phê duyệt': 'approvalNotes',
    'chỉ đạo phê duyệt': 'approvalNotes',
    'ghi chú phê duyệt': 'approvalNotes',
    'approval notes': 'approvalNotes',
    'ghi chú': 'approvalNotes',
    notes: 'approvalNotes',
  },

  departments: {
    'mã đơn vị': 'code',
    mã: 'code',
    code: 'code',
    'unit code': 'code',
    'department code': 'code',
    'tên đơn vị': 'name',
    tên: 'name',
    name: 'name',
    'unit name': 'name',
    'department name': 'name',
    'loại đơn vị': 'unitType',
    loại: 'unitType',
    unittype: 'unitType',
    'unit type': 'unitType',
    'đơn vị cha': 'parent',
    parent: 'parent',
    'parent unit': 'parent',
    'đơn vị cha id': 'parentId',
    parentid: 'parentId',
    'parent id': 'parentId',
    'chức năng nhiệm vụ': 'functions',
    'chức năng': 'functions',
    'nhiệm vụ': 'functions',
    functions: 'functions',
    'trạng thái': 'status',
    status: 'status',
    'mô tả': 'description',
    'mô tả chức năng': 'description',
    description: 'description',
    vùng: 'region',
    'vùng quản lý': 'region',
    'vùng quản lý new': 'region',
    'vùng quản lý old': 'region',
    region: 'region',
  },

  users: {
    'tên đăng nhập': 'username',
    username: 'username',
    'họ và tên': 'fullName',
    'họ tên': 'fullName',
    fullname: 'fullName',
    'full name': 'fullName',
    email: 'email',
    'số điện thoại': 'phone',
    sđt: 'phone',
    phone: 'phone',
    'vai trò': 'role',
    role: 'role',
    'phòng ban': 'department',
    'bộ phận': 'department',
    legacyDepartment: 'department',
    'chức danh': 'jobTitle',
    jobtitle: 'jobTitle',
    'job title': 'jobTitle',
    'nơi làm việc': 'workplace',
    workplace: 'workplace',
    'mã nhân viên': 'employeeId',
    employeeid: 'employeeId',
    'employee id': 'employeeId',
  },

  'audit-universe': {
    'tên quy trình / hoạt động': 'name',
    'tên quy trình': 'name',
    'tên hoạt động': 'name',
    'process / activity name': 'name',
    'đơn vị phụ trách': 'department',
    'phòng phụ trách': 'department',
    'đơn vị': 'department',
    'department in charge': 'department',
    'mã đơn vị phụ trách': 'departmentCode',
    departmentcode: 'departmentCode',
    'department code': 'departmentCode',
    'quy mô tài sản/gd (1–10)': 'financialSize',
    'quy mô tài sản gd': 'financialSize',
    'quy mô tài sản': 'financialSize',
    'quy mô': 'financialSize',
    financialsize: 'financialSize',
    'financial size (1-10)': 'financialSize',
    'rủi ro vận hành t2 (1–10)': 'operationalRiskScore',
    'rủi ro vận hành': 'operationalRiskScore',
    operationalriskscore: 'operationalRiskScore',
    'operational risk (1-10)': 'operationalRiskScore',
    'sai phạm lịch sử (1–10)': 'pastFindingsScore',
    'sai phạm lịch sử': 'pastFindingsScore',
    pastfindingsscore: 'pastFindingsScore',
    'past findings (1-10)': 'pastFindingsScore',
    'ngày kiểm toán gần nhất': 'lastAuditDate',
    'ngày kiểm toán': 'lastAuditDate',
    lastauditdate: 'lastAuditDate',
    'last audit date': 'lastAuditDate',
    'năm kt tiếp theo': 'nextAuditYear',
    'năm kiểm toán': 'nextAuditYear',
    'năm kt': 'nextAuditYear',
    nextaudityear: 'nextAuditYear',
    'next audit year': 'nextAuditYear',
    'phân loại': 'auditCategory',
    auditcategory: 'auditCategory',
    'audit category': 'auditCategory',
    'phòng ktnb phụ trách': 'ownerTeam',
    'phòng ktnb': 'ownerTeam',
    ownerteam: 'ownerTeam',
    'internal audit team': 'ownerTeam',
    'tuyến phòng thủ': 'lineOfDefense',
    lineofdefense: 'lineOfDefense',
    'line of defense': 'lineOfDefense',
  },

  'risk-criteria': {
    'tên tiêu chí': 'name',
    'criteria name': 'name',
    'trọng số': 'weight',
    weight: 'weight',
    'phân loại rủi ro': 'category',
    category: 'category',
    'risk category': 'category',
    'phân loại đối tượng': 'auditCategory',
    'nhóm kiểm toán': 'auditCategory',
    'audit group': 'auditCategory',
    'mô tả chi tiết': 'description',
    'mô tả': 'description',
  },

  'risk-assessments': {
    'quy trình / đơn vị': 'universeName',
    'quy trình': 'universeName',
    universename: 'universeName',
    'process / unit': 'universeName',
    'mã quy trình / đối tượng': 'auditUniverseId',
    'mã quy trình': 'auditUniverseId',
    'mã đối tượng': 'auditUniverseId',
    audituniverseid: 'auditUniverseId',
    'process id': 'auditUniverseId',
    'phòng ban chịu trách nhiệm': 'department',
    'nhóm kiểm toán': 'auditCategory',
    'nhóm kt': 'auditCategory',
    năm: 'assessmentYear',
    'năm đánh giá': 'assessmentYear',
    assessmentyear: 'assessmentYear',
    'assessment year': 'assessmentYear',
    'tổng điểm': 'totalScore',
    'điểm inherent': 'totalScore',
    'inherent risk': 'totalScore',
    totalscore: 'totalScore',
    'mức độ rủi ro': 'riskLevel',
    'mức rủi ro': 'riskLevel',
    'hạng rủi ro': 'riskLevel',
    risklevel: 'riskLevel',
    'risk level': 'riskLevel',
    'ảnh hưởng': 'impact',
    impact: 'impact',
    'khả năng': 'likelihood',
    likelihood: 'likelihood',
    'hiệu quả kiểm soát': 'controlEffectiveness',
    'kiểm soát': 'controlEffectiveness',
    controleffectiveness: 'controlEffectiveness',
    'control effectiveness': 'controlEffectiveness',
    'rủi ro còn lại': 'residualRiskScore',
    'điểm rủi ro còn lại': 'residualRiskScore',
    residualriskscore: 'residualRiskScore',
    'residual risk score': 'residualRiskScore',
    'tần suất kt': 'auditFrequency',
    'tần suất kiểm toán': 'auditFrequency',
    'tần suất đề xuất': 'auditFrequency',
    'tần suất': 'auditFrequency',
    auditfrequency: 'auditFrequency',
    'audit frequency': 'auditFrequency',
    'tốc độ rủi ro': 'riskVelocity',
    'tốc độ biến động rr': 'riskVelocity',
    'tốc độ biến động rủi ro': 'riskVelocity',
    riskvelocity: 'riskVelocity',
    'risk velocity': 'riskVelocity',
    'hạn mức chấp nhận rủi ro': 'riskAppetite',
    'khẩu vị rủi ro': 'riskAppetite',
    riskappetite: 'riskAppetite',
    'risk appetite': 'riskAppetite',
    'ghi chú': 'notes',
    'ghi chú đánh giá': 'notes',
    notes: 'notes',
    'biện pháp giảm thiểu': 'mitigationPlan',
    'kế hoạch giảm thiểu rủi ro': 'mitigationPlan',
    'kế hoạch giảm thiểu': 'mitigationPlan',
    mitigationplan: 'mitigationPlan',
    'mitigation plan': 'mitigationPlan',
    'mô tả rủi ro chi tiết': 'riskDescription',
    'mô tả rủi ro chính': 'riskDescription',
    'mô tả rủi ro': 'riskDescription',
    riskdescription: 'riskDescription',
    'risk description': 'riskDescription',
  },

  'risk-control-matrix': {
    'tên quy trình': 'processName',
    'quy trình': 'processName',
    processname: 'processName',
    'process name': 'processName',
    'quy trình con': 'subProcess',
    subprocess: 'subProcess',
    'sub process': 'subProcess',
    'mục tiêu kinh doanh': 'businessObjective',
    businessobjective: 'businessObjective',
    'business objective': 'businessObjective',
    'tên rủi ro': 'riskName',
    riskname: 'riskName',
    'risk name': 'riskName',
    'mô tả rủi ro': 'riskDescription',
    'risk description': 'riskDescription',
    riskdescription: 'riskDescription',
    'điểm rủi ro gốc': 'inherentRiskScore',
    'mức độ rủi ro': 'inherentRiskScore',
    'mức độ rủi ro tiềm tàng': 'inherentRiskScore',
    inherentriskscore: 'inherentRiskScore',
    'inherent risk score': 'inherentRiskScore',
    'tên chốt kiểm soát': 'controlName',
    'chốt kiểm soát': 'controlName',
    'mô tả chốt kiểm soát': 'controlDescription',
    'mô tả kiểm soát': 'controlDescription',
    'đặc tính chốt': 'controlType',
    'loại chốt': 'controlType',
    'loại kiểm soát': 'controlType',
    'tần suất': 'controlFrequency',
    'tần suất kiểm soát': 'controlFrequency',
    'mức độ tự động hóa': 'controlAutomation',
    'mức độ tự động': 'controlAutomation',
    'tự động hóa': 'controlAutomation',
    'thủ tục kiểm tra': 'testProcedure',
    'thủ tục kiểm toán': 'testProcedure',
    'thủ tục dự kiến': 'testProcedure',
    'bằng chứng kỳ vọng': 'expectedEvidence',
    'bằng chứng mong đợi': 'expectedEvidence',
  },

  transactions: {
    'mã giao dịch': 'transactionCode',
    'transaction code': 'transactionCode',
    'mã tài khoản': 'accountId',
    'account id': 'accountId',
    'tên khách hàng': 'customerName',
    'customer name': 'customerName',
    'tên nhà cung cấp': 'vendorName',
    'vendor name': 'vendorName',
    'số tiền': 'amount',
    amount: 'amount',
    'thời gian': 'transactionDate',
    ngày: 'transactionDate',
    'transaction date': 'transactionDate',
    ip: 'ipAddress',
    'mô tả': 'description',
  },

  controls: {
    'chốt kiểm soát': 'controlName',
    controlname: 'controlName',
    'control name': 'controlName',
    'mô tả chốt kiểm soát': 'controlDescription',
    'control description': 'controlDescription',
    controldescription: 'controlDescription',
    'loại kiểm soát': 'controlType',
    controltype: 'controlType',
    'control type': 'controlType',
    'mức độ tự động': 'controlAutomation',
    controlautomation: 'controlAutomation',
    'control automation': 'controlAutomation',
    'tần suất': 'controlFrequency',
    controlfrequency: 'controlFrequency',
    'control frequency': 'controlFrequency',
    'thủ tục kiểm tra': 'testProcedure',
    'thủ tục kiểm toán': 'testProcedure',
    testprocedure: 'testProcedure',
    'test procedure': 'testProcedure',
    'bằng chứng mong đợi': 'expectedEvidence',
    'bằng chứng': 'expectedEvidence',
    expectedevidence: 'expectedEvidence',
    'expected evidence': 'expectedEvidence',
  },

  'audit-rules': {
    'rule id': 'ruleId',
    ruleid: 'ruleId',
    'mã luật': 'ruleId',
    'mã quy tắc': 'ruleId',
    'mã luật giám sát': 'ruleId',
    'mảng nghiệp vụ': 'domain',
    'phân hệ': 'domain',
    domain: 'domain',
    'nghiệp vụ': 'domain',
    'tên luật giám sát': 'ruleName',
    'tên luật': 'ruleName',
    'tên quy tắc': 'ruleName',
    rulename: 'ruleName',
    'mức độ cảnh báo': 'alertLevel',
    'mức độ': 'alertLevel',
    alertlevel: 'alertLevel',
    'sla xử lý (giờ)': 'slaHours',
    'sla xử lý': 'slaHours',
    'sla (giờ)': 'slaHours',
    sla: 'slaHours',
    slahours: 'slaHours',
    'mô tả rủi ro': 'risk',
    'rủi ro': 'risk',
    risk: 'risk',
    'điều kiện logic': 'logic',
    'logic kiểm tra': 'logic',
    logic: 'logic',
    'tần suất': 'frequency',
    frequency: 'frequency',
    'hệ thống nguồn': 'sourceSystem',
    sourcesystem: 'sourceSystem',
    'mục tiêu kiểm toán': 'auditObjective',
    auditobjective: 'auditObjective',
  },

  'continuous-monitoring': {
    'rule id': 'ruleId',
    ruleid: 'ruleId',
    'mã luật': 'ruleId',
    'mảng nghiệp vụ': 'domain',
    domain: 'domain',
    'tên luật giám sát': 'ruleName',
    rulename: 'ruleName',
    'mức độ cảnh báo': 'alertLevel',
    alertlevel: 'alertLevel',
    'sla xử lý (giờ)': 'slaHours',
    slahours: 'slaHours',
    'mô tả rủi ro': 'risk',
    risk: 'risk',
    'điều kiện logic': 'logic',
    logic: 'logic',
  },
};

/**
 * Tra cứu trường ánh xạ từ khóa với độ phức tạp O(1)
 */
export function getNormalizedKey(
  module: string,
  rawKey: string,
): string | undefined {
  const map = MODULE_KEY_MAPS[module];
  if (!map) return undefined;
  const cleanKey = rawKey.trim().toLowerCase();
  return map[cleanKey];
}
