import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Query,
  Delete,
  Res,
  UseGuards,
  Request,
  BadRequestException,
} from '@nestjs/common';
import { InjectQueue } from '@nestjs/bullmq';
import { Queue } from 'bullmq';

import { AuditReportsService } from './audit-reports.service';
import { CreateAuditReportDto } from './dto/create-audit-report.dto';
import { UpdateAuditReportDto } from './dto/update-audit-report.dto';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { PoliciesGuard } from '../casl/policies.guard';
import { CheckPolicies } from '../casl/check-policies.decorator';
import { Action } from '../casl/casl-ability.factory';
import { AuditTrailService } from '../audit-trail/audit-trail.service';
import { NotificationsService } from '../notifications/notifications.service';

@Controller('audit-reports')
@UseGuards(JwtAuthGuard, PoliciesGuard)
export class AuditReportsController {
  constructor(
    private readonly auditReportsService: AuditReportsService,
    private readonly auditTrailService: AuditTrailService,
    private readonly notificationsService: NotificationsService,
    @InjectQueue('reports') private readonly reportsQueue: Queue,
  ) {}

  @Post()
  @CheckPolicies((ability) => ability.can(Action.Create, 'Report'))
  async create(@Body() dto: CreateAuditReportDto, @Request() req: any) {
    const result = await this.auditReportsService.create(dto);
    await this.auditTrailService.log({
      action: 'CREATE',
      resource: 'audit-reports',
      resourceId: (result as any)?.id,
      userId: req.user?.userId,
      username: req.user?.username,
      newValue: { title: dto.title },
    });
    return result;
  }

  /** Auto-generate report from engagement findings */
  @Post('auto-generate')
  @CheckPolicies((ability) => ability.can(Action.Create, 'Report'))
  async autoGenerate(
    @Body() body: { engagementId: number; title: string; plan?: string },
    @Request() req: any,
  ) {
    const result = await this.auditReportsService.autoGenerate(
      body.engagementId,
      body.title,
      body.plan,
    );
    await this.auditTrailService.log({
      action: 'CREATE',
      resource: 'audit-reports',
      resourceId: (result as any)?.id,
      userId: req.user?.userId,
      username: req.user?.username,
      newValue: { title: body.title, autoGenerated: true },
    });
    return result;
  }

  @Get()
  @CheckPolicies((ability) => ability.can(Action.Read, 'Report'))
  findAll(@Request() req: any) {
    return this.auditReportsService.findAll(req.user);
  }

  @Get('glossary')
  @CheckPolicies((ability) => ability.can(Action.Read, 'Report'))
  async exportGlossary(@Res() res: any) {
    try {
      const docx = require('docx');
      const doc = new docx.Document({
        sections: [
          {
            children: [
              new docx.Paragraph({
                children: [new docx.TextRun('Thuyết minh báo cáo kiểm toán')],
              }),
            ],
          },
        ],
      });
      const buffer = await docx.Packer.toBuffer(doc);
      res.headers({
        'Content-Type':
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': 'attachment; filename=BA01_Thuyet_minh.docx',
      });
      res.send(buffer);
    } catch (error) {
      res.status(500).send({ message: 'Lỗi xuất file thuyết minh' });
    }
  }

  // Export routes MUST be BEFORE :id to avoid NestJS matching "export" as an id
  @Get(':id/export/word')
  @CheckPolicies((ability) => ability.can(Action.Read, 'Report'))
  async exportWord(
    @Param('id') id: string,
    @Query('type') type: string,
    @Res() res: any,
  ) {
    try {
      const buffer = await this.auditReportsService.generateWord(+id, type);
      const prefix = type ? `${type}_` : 'BCKT_';
      res.headers({
        'Content-Type':
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename=${prefix}${id}.docx`,
      });
      res.send(buffer);
    } catch (error) {
      res.status(500).send({ message: 'Lỗi xuất file word' });
    }
  }

  @Get(':id/export/pdf')
  @CheckPolicies((ability) => ability.can(Action.Read, 'Report'))
  async exportPdf(@Param('id') id: string, @Res() res: any) {
    try {
      const buffer = await this.auditReportsService.generatePdf(+id);
      res.headers({
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=Bao_cao_kiem_toan_${id}.pdf`,
      });
      res.send(buffer);
    } catch (error) {
      res.status(500).send({ message: 'Lỗi xuất file pdf' });
    }
  }

  @Get(':id')
  @CheckPolicies((ability) => ability.can(Action.Read, 'Report'))
  findOne(@Param('id') id: string) {
    return this.auditReportsService.findOne(+id);
  }

  @Patch(':id')
  @CheckPolicies((ability) => ability.can(Action.Update, 'Report'))
  async update(
    @Param('id') id: string,
    @Body() dto: UpdateAuditReportDto,
    @Request() req: any,
  ) {
    const result = await this.auditReportsService.update(+id, dto);
    await this.auditTrailService.log({
      action: 'UPDATE',
      resource: 'audit-reports',
      resourceId: +id,
      userId: req.user?.userId,
      username: req.user?.username,
      newValue: dto,
    });
    return result;
  }

  /** Workflow status transition: Draft → PendingReview → Reviewed → Issued */
  @Post(':id/transition')
  @CheckPolicies((ability) => ability.can(Action.Manage, 'Report'))
  async transition(
    @Param('id') id: string,
    @Body() body: { newStatus: string },
    @Request() req: any,
  ) {
    const oldReport = await this.auditReportsService.findOne(+id);
    const result = await this.auditReportsService.changeStatus(
      +id,
      body.newStatus,
      req.user?.userId,
      req.user?.username,
    );

    await this.auditTrailService.log({
      action: 'UPDATE',
      resource: 'audit-reports',
      resourceId: +id,
      userId: req.user?.userId,
      username: req.user?.username,
      oldValue: { status: oldReport?.status },
      newValue: { status: body.newStatus },
    });

    return result;
  }

  /** Chữ ký số (Digital Signature - Xử lý ngầm) */
  @Post(':id/sign')
  @CheckPolicies((ability) => ability.can(Action.Manage, 'Report'))
  async sign(@Param('id') id: string, @Request() req: any) {
    const job = await this.reportsQueue.add('sign-report', {
      action: 'signReport',
      reportId: +id,
      username: req.user?.username,
    });
    return { message: 'Đã đưa yêu cầu ký số vào hàng đợi', jobId: job.id };
  }

  // ===== IIA Standard 6.3: Report Distribution Endpoints =====
  @Post(':id/distribute')
  @CheckPolicies((ability) => ability.can(Action.Manage, 'Report'))
  async distribute(
    @Param('id') id: string,
    @Body('recipients') recipients: any[],
    @Request() req: any,
  ) {
    const result = await this.auditReportsService.distributeReport(+id, recipients);
    await this.auditTrailService.log({
      action: 'UPDATE',
      resource: 'audit-reports',
      resourceId: +id,
      userId: req.user?.userId,
      username: req.user?.username,
      newValue: { distributedCount: recipients?.length },
    });
    return result;
  }

  @Get(':id/distributions')
  getDistributions(@Param('id') id: string) {
    return this.auditReportsService.getDistributions(+id);
  }

  @Get(':id/distributions/stats')
  getDistributionStats(@Param('id') id: string) {
    return this.auditReportsService.getDistributionStats(+id);
  }

  @Post('distributions/:distId/read')
  markRead(@Param('distId') distId: string) {
    return this.auditReportsService.markReportRead(+distId);
  }

  @Post('distributions/:distId/acknowledge')
  acknowledge(
    @Param('distId') distId: string,
    @Body('notes') notes: string,
  ) {
    return this.auditReportsService.acknowledgeReport(+distId, notes);
  }

  @Delete(':id')
  @CheckPolicies((ability) => ability.can(Action.Delete, 'Report'))
  async remove(@Param('id') id: string, @Request() req: any) {
    await this.auditTrailService.log({
      action: 'DELETE',
      resource: 'audit-reports',
      resourceId: +id,
      userId: req.user?.userId,
      username: req.user?.username,
    });
    return this.auditReportsService.remove(+id);
  }
}
